In [1]:
#Project 1 for Statistical Learning - Residency 1

In [ ]:
# Think of yourself, currently working as a Business analyst in one of the top sports company. The senior management team has asked you to come up with metrics with which they can gauge which team will win the upcoming La Liga cup (Football tournament).
# The data set contains information on all the teams so far participated in all the past tournaments. It has data about how many goals each team scored, conceded, how many times they came within first 6 positions, how many seasons they have qualified, their best position in the past etc.

In [3]:
# Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)

In [10]:
import pandas as pd

df = pd.read_csv("Laliga.csv")

In [11]:
df.head(10)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
5,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
6,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,-,-,4,5,2,5,16,1929,1994-95,3
7,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
8,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,-,1,4,5,4,4,18,1939-40,2012-13,2
9,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,-,2,3,4,4,14,1932-33,2015-16,1

In [16]:
for column in df:
    df[column] = df[column].replace("-",'0')
df.head(20)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1
5,6,Sevilla,73,2819,2408,990,531,887,3680,3373,1,4,4,5,12,6,32,1934-35,2001-02,1
6,7,Espanyol,82,2792,2626,948,608,1070,3609,3889,0,0,4,5,2,5,16,1929,1994-95,3
7,8,Real Sociedad,70,2573,2302,864,577,861,3228,3230,2,3,2,5,4,3,19,1929,2010-11,1
8,9,Zaragoza,58,2109,1986,698,522,766,2683,2847,0,1,4,5,4,4,18,1939-40,2012-13,2
9,10,Real Betis,51,1884,1728,606,440,682,2159,2492,1,0,2,3,4,4,14,1932-33,2015-16,1
10,11,Deportivo La Coruna,45,1814,1530,563,392,575,2052,2188,1,5,4,1,0,1,12,1941-42,2014-15,1
11,12,Celta Vigo,51,1789,1698,586,389,723,2278,2624,0,0,0,2,4,5,11,1939-40,2012-13,4
12,13,Valladolid,42,1471,1466,463,384,619,1767,2180,0,0,0,1,1,1,3,1948-49,2013-14,4
13,14,Racing Santander,44,1416,1428,453,336,639,1843,2368,0,1,1,2,0,1,5,1929,2011-12,2
14,15,Sporting Gijon,43,1389,1458,471,358,629,1753,2152,0,1,1,2,2,1,7,1944-45,2015-16,2
15,16,Osasuna,37,1351,1318,426,327,565,1500,1834,0,0,0,2,2,2,6,1935-36,2016-17,4
16,17,Malaga,36,1314,1255,390,330,535,1421,1763,0,0,0,1,0,1,2,1949-50,2008-09,4
17,18,Oviedo,38,1174,1192,408,292,492,1642,1951,0,0,3,2,2,4,11,1933-34,2000-01,3
18,19,Mallorca,27,1148,988,333,256,399,1182,1371,0,0,2,0,2,1,5,1960-61,2012-13,3
19,20,Las Palmas,33,1020,1096,367,242,487,1347,1746,0,1,1,1,1,1,5,1951-52,2015-16,2

In [120]:
#Print all the teams which have started playing between 1930-1980. (5 points)

In [142]:
df_team = []
for i in df.index:
    deb_yr = int(df.get_value(i,'Debut'))
    if(deb_yr >= 1930 and deb_yr <= 1980):
       df_team.append({'Team':df.get_value(i,'Team'), 'Debut': deb_yr})
df_team = pd.DataFrame(df_team)
df_team

C:\Users\Suchi\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Suchi\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """

    Debut                 Team
0    1931             Valencia
1    1934              Sevilla
2    1939             Zaragoza
3    1932           Real Betis
4    1941  Deportivo La Coruna
5    1939           Celta Vigo
6    1948           Valladolid
7    1944       Sporting Gijon
8    1935              Osasuna
9    1949               Malaga
10   1933               Oviedo
11   1960             Mallorca
12   1951           Las Palmas
13   1941              Granada
14   1977       Rayo Vallecano
15   1959                Elche
16   1935             Hercules
17   1961             Tenerife
18   1940               Murcia
19   1930               Alaves
20   1963              Levante
21   1974            Salamanca
22   1943             Sabadell
23   1977                Cadiz
24   1941            Castellon
25   1962              Cordoba
26   1978           Recreativo
27   1971            Burgos CF
28   1963           Pontevedra
29   1947            Gimnastic
30   1945             Alcoyano
31   1953                 Jaen
32   1979           AD Almeria
33   1950               Lleida
34   1956               Condal
35   1951      Atletico Tetuan
36   1955     Cultural Leonesa

In [134]:
#Print the list of teams which came Top 5 in terms of points (2.5 points)

In [21]:
df.sort_values('Points', ascending=False).head(5)[['Team', 'Points']]

           Team Points
20   Villarreal    970
45  Real Burgos     96
46    Gimnastic     91
47  Extremadura     83
48       Merida     81

In [22]:
#Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)

In [99]:
def Goal_diff_count(df1):
    df_team = []
    for i in df1.index:
        diff = int(df1.get_value(i,'GoalsFor')) - int(df1.get_value(i,'GoalsAgainst'))
        df_team.append({'Team':df1.get_value(i,'Team'), 'Diff': diff})
    return pd.DataFrame(df_team)

In [100]:
df_ret = Goal_diff_count(df)
df_ret[["Diff"]] = df_ret[["Diff"]].apply(pd.to_numeric)
df_ret.sort_values(by='Diff',axis=0,ascending=False).tail(5)

C:\Users\Suchi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.
C:\Users\Suchi\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """

    Diff              Team
27  -385            Murcia
19  -399        Las Palmas
14  -399    Sporting Gijon
12  -413        Valladolid
13  -525  Racing Santander

In [101]:
#Create a new column with name “Winning Percent” and append it to the data set (5 points)

In [115]:
df["Winning Percent"] = (df["GamesWon"].astype(int)/df["GamesPlayed"].astype(int)) * 100
df["Winning Percent"].fillna(0, inplace=True)
df.sort_values(by="Winning Percent", ascending = False).head(5)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,...,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition,diff,Winning Percent
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,...,8,8,3,4,79,1929,1929,1,2807,59.630702
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,...,12,12,4,6,83,1929,1929,1,2786,57.241130
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,...,16,9,7,6,56,1929,2002-03,1,1225,47.475134
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,...,10,11,10,7,50,1931-32,1987-88,1,929,44.557057
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,...,10,5,8,10,49,1929,1929,1,931,43.772629

In [116]:
#Group teams based on their “Best position” and print the sum of their points for all positions (10 points)

In [119]:
df.groupby(['BestPosition','Team'])['Points'].agg('sum')

BestPosition  Team
1             Athletic Bilbao        3368
              Atletico Madrid        3442
              Barcelona              4262
              Deportivo La Coruna    1814
              Real Betis             1884
              Real Madrid            4385
              Real Sociedad          2573
              Sevilla                2819
              Valencia               3386
2             Las Palmas             1020
              Racing Santander       1416
              Sporting Gijon         1389
              Villarreal              970
              Zaragoza               2109
3             Arenas                  107
              Espanyol               2792
              Mallorca               1148
              Oviedo                 1174
4             Castellon               285
              Celta Vigo             1789
              Malaga                 1314
              Osasuna                1351
              Sabadell                353
              Valladolid             1471
5             Cordoba                 230
              Elche                   606
              Hercules                538
              Tenerife                510
6             Alaves                  421
              Getafe                  553
                                     ...
              Levante                 416
              Real Union               56
7             Albacete                277
              Gimnastic                91
              Logrones                293
              Pontevedra              150
              Salamanca               375
8             Almeria                 242
              Europa                   42
              Rayo Vallecano          662
              Recreativo              188
9             Girona                    0
              Real Burgos              96
10            AD Almeria               52
              Alcoyano                 76
              Compostela              190
              Eibar                   132
11            Murcia                  445
12            Burgos CF               168
              Cadiz                   343
14            Jaen                     71
15            Cultural Leonesa         14
16            Atletico Tetuan          19
              Condal                   22
              Lleida                   40
17            Extremadura              83
              Leganes                  35
              Numancia                148
19            Merida                   81
20            Xerez                    34
Name: Points, Length: 61, dtype: object